# Generated by Django 2.1.2 on 2018-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='many_to_many.Topping'),
        ),
    ]
