# Generated by Django 2.1.2 on 2018-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0002_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='relation_users',
            field=models.ManyToManyField(related_name='_twitteruser_relation_users_+', through='many_to_many.Relation', to='many_to_many.TwitterUser'),
        ),
    ]
